# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petugas', '0002_auto_20180411_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surat_Keluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_surat', models.CharField(max_length=30)),
                ('tanggal_kirim', models.DateField()),
                ('no_surat', models.CharField(max_length=15)),
                ('pengirim', models.CharField(max_length=30)),
                ('perihal', models.CharField(max_length=30)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petugas.Petugas')),
            ],
        ),
        migrations.CreateModel(
            name='Surat_Masuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_surat', models.CharField(max_length=30)),
                ('tanggal_kirim', models.DateField()),
                ('tanggal_terima', models.DateField()),
                ('no_surat', models.CharField(max_length=15)),
                ('pengirim', models.CharField(max_length=30)),
                ('perihal', models.CharField(max_length=30)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petugas.Petugas')),
            ],
        ),
    ]
