# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Surat_Keluar',
            new_name='SuratKeluar',
        ),
        migrations.RenameModel(
            old_name='Surat_Masuk',
            new_name='SuratMasuk',
        ),
    ]
