# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petugas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petugas',
            old_name='uname',
            new_name='username',
        ),
    ]
